---
# yaml-language-server: $schema=https://github.com/games-on-whales/fenrir/raw/refs/heads/main/schemas/direwolf.games-on-whales.github.io/user_v1alpha1.json
apiVersion: direwolf.games-on-whales.github.io/v1alpha1
kind: User
metadata:
  name: alex
  namespace: direwolf
spec:
  volumes:
    - name: fix-home-perms
      configMap:
        name: fix-home-perms
        defaultMode: 0755
  resources:
    limits:
      squat.ai/dri: "1"
      cpu: 4000m
      memory: 8G
    requests:
      squat.ai/dri: "1"
      cpu: 4000m
      memory: 8G
  sidecarPolicies:
    # We are overriding the default resources for some sidecars for this user.
    wolf:
      # I'm using generic devices to pass along the gpu.
      resources:
        requests:
          squat.ai/dri: "1"
          squat.ai/uinput: "1"
          cpu: 2
          memory: 2G
        limits:
          squat.ai/dri: "1"
          squat.ai/uinput: "1"
          cpu: 2
          memory: 2G
      volumeMounts:
        - name: fix-home-perms
          mountPath: /etc/cont-init.d/99-fix-home-perms.sh
          subPath: 99-fix-home-perms.sh
          readOnly: true
