apiVersion: skaffold/v4beta7
kind: Config
build:
  artifacts:
    - image: localhost:5001/direwolf-operator-dev
      context: .
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          APP_NAME: operator
      sync:
        manual:
          - src: 'pkg/**/*.go'
            dest: .
          - src: 'cmd/operator/main.go'
            dest: .
          - src: 'go.mod'
            dest: .
          - src: 'go.sum'
            dest: .
    - image: localhost:5001/direwolf-moonlight-dev
      context: .
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          APP_NAME: moonlight-proxy
      sync:
        manual:
          - src: 'pkg/**/*.go'
            dest: .
          - src: 'cmd/moonlight-proxy/main.go'
            dest: .
          - src: 'go.mod'
            dest: .
          - src: 'go.sum'
            dest: .
  local:
    push: true
## To prevent skaffold from copying into the non active profile
profiles:
  - name: operator
    patches:
      - op: remove
        path: /build/artifacts/1/sync
  - name: moonlight
    patches:
      - op: remove
        path: /build/artifacts/0/sync

deploy:
  kubectl:
    flags:
      apply:
        - "--server-side"
manifests:
  rawYaml:
  - ./hack/devbox.yaml
  - ./crds/*

portForward:
  ## For the streaming service there should be more? since both services share all ports
  ## This is until we migrate to ingress or api
  - resourceType: Service
    resourceName: direwolf
    port: 47984
    localPort: 47984
  - resourceType: Service
    resourceName: direwolf
    port: 47989
    localPort: 47989
  ## For dlv, probably in the future once I get this whole operator development down
  - resourceType: Deployment
    resourceName: direwolf-operator-dev
    port: 2345
    localPort: 2345