kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: direwolf-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.35.0
    extraMounts:
      - hostPath: /tmp/wolf/dra1
        containerPath: /etc/dra
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        taints: []
    - |
      kind: JoinConfiguration
      nodeRegistration:
        taints: []
  - role: worker
    image: kindest/node:v1.35.0
    extraMounts:
      - hostPath: /tmp/wolf/dra2
        containerPath: /etc/dra
featureGates:
  DynamicResourceAllocation: true
  DRAConsumableCapacity: true