---
# yaml-language-server: $schema=https://github.com/games-on-whaless/fenrir/raw/refs/heads/main/schemas/direwolf.games-on-whales.github.io/user_v1alpha1.json
apiVersion: direwolf.games-on-whales.github.io/v1alpha1
kind: User
metadata:
  name: alex
  namespace: direwolf
spec:
  # hostPath volume for the input, this is for testing
  volumes:
   - name: dev-input
     hostPath:
       path: /dev/input
       type: File
   - name: host-udev
     hostPath:
       path: /run/udev
       type: Directory
  sidecarPolicies:
    # Define policies for the 'wolf' sidecar container.
    wolf:
      # Define resource requests and limits.
      # give it the GPU device via nvidia operator plugin.
      resources:
        requests:
          nvidia.com/gpu: "1"
        limits:
          nvidia.com/gpu: "1"
      # # Mount the hostPath volumes defined above into the 'wolf' sidecar
      volumeMounts:
        - name: dev-input
          mountPath: /dev/input
        - name: host-udev
          mountPath: /run/udev