---
# yaml-language-server: $schema=https://github.com/games-on-whales/fenrir/raw/refs/heads/main/schemas/direwolf.games-on-whales.github.io/user_v1alpha1.json
apiVersion: direwolf.games-on-whales.github.io/v1alpha1
kind: User
metadata:
  name: alex
  namespace: direwolf
spec:
  resources:
    limits:
      nvidia.com/gpu: "1"
      cpu: 4000m
      memory: 8G
    requests:
      nvidia.com/gpu: "1"
      cpu: 4000m
      memory: 8G
  sidecarPolicies:
    # We are overriding the default resources for some sidecars for this user.
    wolf:
      # # add needed runtime env vars
      env:
      - name: NVIDIA_DRIVER_CAPABILITIES
        value: all
      - name: NVIDIA_VISIBLE_DEVICES
        value: all
      resources:
        requests:
          nvidia.com/gpu: "1"
          squat.ai/uinput: "1"
          cpu: 1000m
          memory: 2G
        limits:
          nvidia.com/gpu: "1"
          squat.ai/uinput: "1"
          cpu: 1000m
          memory: 2G
      ## Not needed most of the time.
      # securityContext:
      #   privileged: true
    # pulseaudio: